scrolling_text/scrolling_text/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('ticker.urls')),
    path('admin/', admin.site.urls),
]

scrolling_text/ticker/urls.py
from django.urls import path
from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
]

scrolling_text/ticker/models.py
from django.db import models


class Video(models.Model):
    name = models.CharField(max_length=255)
    file = models.FileField(upload_to='videos/')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class RunningTextHistory(models.Model):
    text = models.CharField(max_length=40)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

scrolling_text/ticker/views.py
import os

from django.shortcuts import render
from django.http import HttpResponse
from .utils import create_running_text_video
from .models import RunningTextHistory


def index(request):
    if request.method == 'POST':
        text = request.POST.get('text', '')
        text_color = request.POST.get('text_color', '#000000')
        bg_color = request.POST.get('bg_color', '#0000FF')
        if not (1 <= len(text) <= 40):
            return HttpResponse('Количество символов должно быть от 1 до 40', status=400)
        width = 100
        height = 100
        duration = 3
        video_response = create_running_text_video(text, text_color, bg_color, width, height, duration)
        if video_response:
            history_entry = RunningTextHistory(text=text)
            history_entry.save()
            with open(video_response, 'rb') as file:
                response = HttpResponse(file.read(), content_type='video/mp4')
                name = "running_text.mp4"
                response['Content-Disposition'] = f'attachment; filename={name}'
                file.close()
                os.remove(video_response)
                return response
    return render(request, 'ticker/index.html')

scrolling_text/templates/ticker/index.html
<!DOCTYPE html>
<html>
<head>    
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #F5F5F5;
            margin: 0;
            padding: 20px;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
        }
        
        h1 {
            color: #333333;
        }
        
        form {
            width: 100%;
            max-width: 400px;
            padding: 20px;
            background-color: #FFFFFF;
            border-radius: 4px;
            box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
        }
        
        label {
            display: block;
            margin-bottom: 10px;
            font-weight: bold;
        }
        
        textarea {
            padding: 10px;
            border-radius: 4px;
            border: 1px solid #CCCCCC;
            width: 100%;
            box-sizing: border-box;
            margin-bottom: 10px;
            resize: vertical;
        }
        
        input[type="color"] {            
            border-radius: 4px;
            border: 1px solid #CCCCCC;
            width: 100%;
            box-sizing: border-box;
            margin-bottom: 10px;
        }
        
        input[type="submit"] {
            padding: 10px 20px;
            background-color: #4CAF50;
            color: #FFFFFF;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            width: 100%;
        }
        
        input[type="submit"]:hover {
            background-color: #45a049;
        }
    </style>
</head>
<body>    
    <form method="post" action="{% url 'app:index' %}">
        {% csrf_token %}
        <label for="text">Текст:</label>
        <textarea id="text" name="text" rows="4" maxlength="50" required></textarea>
        <br>
        <label for="text_color">Цвет текста:</label>
        <input type="color" id="text_color" name="text_color" value="#000000" required>
        <br>
        <label for="bg_color">Цвет фона:</label>
        <input type="color" id="bg_color" name="bg_color" value="#FFFFFF" required>
        <br>
        <input type="submit" value="Создать видео">
    </form>
</body>
</html>